version: "3"
services:
  plex:
    dns: 192.168.1.21
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env_file: ./plex.env
    # environment:
    #   - TZ=us
    #   - PLEX_CLAIM=<claimToken>
    #   - ADVERTISE_IP=http://192.168.1.20:32400/
    hostname: plex
    volumes:
      - /mnt/data/plex/config:/config
      - /mnt/data/plex/temp:/transcode
      - /mnt/data/:/data
    networks:
      - vmnw
networks:
  vmnw:
    external:
      name: vm_nw
